### ISSUE TITLE
Any plans to update to latest Hyperapp version?

### ISSUE THREAD

**Issue by drejohnson** [yawaramin/bs-hyperapp#1]
Hi, I see that this is tied to a very old version of hyperapp (v0.12.0). I tried to use this with hyperapp v1.25 but nothing shows on screen. Do you plan to update or is this project dead?

**Comment by yawaramin** [comment]
Hello, I decided not to go ahead with the 'opinionated' approach because Hyperapp has a very clear architecture now post-1.0, and this architecture translates fairly well over to the typed world even without the opinionated guidance of the Elm architecture. I've been experimenting with a Reason binding targeting a post-1.0 version here: https://github.com/yawaramin/re-hyperapp

Two things to note:

1. The binding itself, in `Hyperapp.re`, is super small. Hyperapp exposes a tiny, tiny API surface and expects you to know how to wire it up properly according to its design, and I've been trying to do that
2. You'll see a lot of `[@bs] x => y` style functions in the codebase, nowadays these are just `(. x) => y` thanks to the new syntax.
